Repository primitivefinance/DFMM, pull requests merged in 2024-03, with the labels that each got.

#52 Updates to strategy READMEs and notebooks
  src/ConstantSum/README.md
  src/GeometricMean/README.md
  src/GeometricMean/geometric_mean.nb
  src/GeometricMean/n_token_geometric_mean.nb
  src/LogNormal/README.md
  src/LogNormal/log_normal.nb
Labels: 📚 documentation

#62 Feat/controler swap fees
  src/DFMM.sol
  src/interfaces/IDFMM.sol
  test/ConstantSum/ConstantSumTest.t.sol
  test/ConstantSum/unit/Init.t.sol
  test/ConstantSum/unit/SetUp.sol
  test/DFMM/unit/Deallocate.t.sol
  test/DFMM/unit/Init.t.sol
  test/DFMM/unit/SetUp.sol
  test/DFMM/unit/Swap.t.sol
  test/G3M/fork/G3M.t.sol
  test/G3M/unit/G3M.t.sol
  test/G3M/unit/Init.t.sol
  test/G3M/unit/SetUp.sol
  test/LogNormal/LogNormalTest.t.sol
  test/LogNormal/unit/Init.t.sol
  test/LogNormal/unit/SetUp.sol
  test/NTokenGeometricMean/NTokenGeometricMean.t.sol
Labels: 💡 feature, 📃 contracts

#68 Feat/token checks
  src/DFMM.sol
  src/interfaces/IDFMM.sol
  test/DFMM/unit/Init.t.sol
  test/LogNormal/unit/Init.t.sol
Labels: 🧹 improvement, 📃 contracts

#73 fix: LP tokens minting in `allocate`
  src/DFMM.sol
  test/G3M/unit/Allocate.t.sol
  test/G3M/unit/SetUp.sol
Labels: 📃 contracts, 🔨 audit fix

#74 fix: optimize duplicate tokens loop check
  src/DFMM.sol
Labels: 📃 contracts, 🔨 audit fix

#75 fix: DFMM init now returns the totalLiquidity of the pool
  src/DFMM.sol
  test/DFMM/unit/Init.t.sol
Labels: 📃 contracts, 🔨 audit fix

#77 chore: add commit to OZ clone function link
  src/DFMM.sol
Labels: 📃 contracts, 🔨 audit fix

#79 Fix/compare tokens reserves length
  src/DFMM.sol
  src/interfaces/IDFMM.sol
Labels: 📃 contracts, 🔨 audit fix

#81 fix: typo in _computeDeallocateDeltasGivenDeltaL NatSpec
  src/PairStrategy.sol
Labels: 📃 contracts, 🔨 audit fix

#82 fix: add missing NatSpec to Pool and InitParams structs
  src/interfaces/IDFMM.sol
Labels: 📃 contracts, 🔨 audit fix

#83 Fix/missing constant sum controller
  src/ConstantSum/ConstantSum.sol
  test/ConstantSum/unit/GetPoolParams.t.sol
Labels: 📃 contracts, 🔨 audit fix

#84 Fix ConstantSum strategy
  src/ConstantSum/ConstantSum.sol
  src/ConstantSum/ConstantSumMath.sol
  test/ConstantSum/ConstantSumTest.t.sol
  test/ConstantSum/unit/Allocate.t.sol
  test/ConstantSum/unit/Constructor.t.sol
  test/ConstantSum/unit/GetPoolParams.t.sol
  test/ConstantSum/unit/Init.t.sol
  test/ConstantSum/unit/SetUp.sol
  test/ConstantSum/unit/Swap.t.sol
  test/ConstantSum/unit/Update.t.sol
  test/ConstantSum/unit/ValidateSwap.t.sol
Labels: 📃 contracts, 🔨 audit fix

#85 Fix/reserves length check
  src/ConstantSum/ConstantSum.sol
  src/GeometricMean/G3MMath.sol
  src/GeometricMean/GeometricMean.sol
  src/LogNormal/LogNormal.sol
  src/interfaces/IStrategy.sol
Labels: 📃 contracts, 🔨 audit fix

#86 fix: remove reserveX and reserveY in G3M init struct
  src/GeometricMean/GeometricMean.sol
Labels: 📃 contracts, 🔨 audit fix

#87 fix: use mulDiv to compute G3M deltaLiquidity
  src/GeometricMean/G3MMath.sol
Labels: 📃 contracts, 🔨 audit fix

#76 fix: check if token is WETH in _transferFrom
  src/DFMM.sol
  test/DFMM/unit/Internal.t.sol
Labels: 📃 contracts, 🔨 audit fix

#90 fix: remove unchecked scope for toUint
  src/LogNormal/LogNormalUtils.sol
Labels: 📃 contracts, 🔨 audit fix

#91 fix: use mulDiv to compute deltas in LogNormalMath
  src/LogNormal/LogNormalMath.sol
Labels: 📃 contracts, 🔨 audit fix

#92 fix: rounding in LogNormal trading function
  src/LogNormal/LogNormalMath.sol
Labels: 📃 contracts, 🔨 audit fix

#94 Fix/log normal fixed vars
  src/LogNormal/LogNormalMath.sol
  test/utils/LogNormalArbitrage.sol
Labels: 📃 contracts, 🔨 audit fix

#97 fix: rounding in LogNormal trading function
  src/LogNormal/LogNormalMath.sol
Labels: 📃 contracts, 🔨 audit fix
