Repository primitivefinance/DFMM, pull requests merged in 2024-04, with the labels that each got.

#80 Fix/controller swap fees
  src/DFMM.sol
  test/DFMM/unit/Swap.t.sol
Labels: 📃 contracts, 🔨 audit fix

#98 Fix/minor issues
  src/ConstantSum/ConstantSumMath.sol
  src/ConstantSum/ConstantSumSolver.sol
  src/ConstantSum/ConstantSumUtils.sol
  src/LogNormal/LogNormalMath.sol
  src/NTokenGeometricMean/NTokenGeometricMean.sol
  src/lib/StrategyLib.sol
  test/utils/LogNormalArbitrage.sol
Labels: 📃 contracts, 🔨 audit fix

#102 Fix/g3m weight check
  src/GeometricMean/GeometricMean.sol
Labels: 📃 contracts, 🔨 audit fix

#99 fix: add deltas array length check in NTokenStrategy
  src/NTokenStrategy.sol
Labels: 📃 contracts, 🔨 audit fix

#104 fix: use muldiv in NTokenG3M math
  src/NTokenGeometricMean/NTokenGeometricMeanMath.sol
Labels: 📃 contracts, 🔨 audit fix

#93 Fix/log normal bounded params
  src/LogNormal/LogNormal.sol
Labels: 📃 contracts, 🔨 audit fix

#100 Fix/strategy lib muldiv
  src/lib/StrategyLib.sol
  test/LogNormal/unit/SetUp.sol
Labels: 📃 contracts, 🔨 audit fix

#108 fix: remove computeLGivenY in G3MMath
  src/GeometricMean/G3MMath.sol
  src/GeometricMean/GeometricMeanSolver.sol
Labels: 📃 contracts, 🔨 audit fix

#105 Fix/ntoken accumulator
  src/GeometricMean/GeometricMeanSolver.sol
  src/NTokenGeometricMean/NTokenGeometricMeanMath.sol
  src/NTokenGeometricMean/NTokenGeometricMeanSolver.sol
  test/NTokenGeometricMean/NTokenGeometricMean.t.sol
Labels: 📃 contracts, 🔨 audit fix

#112 fix: optimize token decimals check in DFMM init
  src/DFMM.sol
Labels: 📃 contracts, 🔨 audit fix

#114 fix: computeNextLiquidity in G3MMath
  src/GeometricMean/G3MMath.sol
Labels: 📃 contracts, 🔨 audit fix

#113 fix: NatSpec in computeLGivenX in LogNormalMath
  src/LogNormal/LogNormalMath.sol
Labels: 📃 contracts, 🔨 audit fix

#117 fix: rounding direction in computeTradingFunction in LogNormalMath
  src/LogNormal/LogNormalMath.sol
Labels: 📃 contracts, 🔨 audit fix

#89 Spearbit post-audit fixes
  src/ConstantSum/ConstantSum.sol
  src/ConstantSum/ConstantSumMath.sol
  src/ConstantSum/ConstantSumSolver.sol
  src/ConstantSum/ConstantSumUtils.sol
  src/DFMM.sol
  src/GeometricMean/G3MMath.sol
  src/GeometricMean/GeometricMean.sol
  src/GeometricMean/GeometricMeanSolver.sol
  src/LogNormal/LogNormal.sol
  src/LogNormal/LogNormalMath.sol
  src/LogNormal/LogNormalSolver.sol
  src/LogNormal/LogNormalUtils.sol
  src/NTokenGeometricMean/NTokenGeometricMean.sol
  src/NTokenGeometricMean/NTokenGeometricMeanMath.sol
  src/NTokenGeometricMean/NTokenGeometricMeanSolver.sol
  src/NTokenGeometricMean/NTokenGeometricMeanUtils.sol
  src/NTokenStrategy.sol
  src/PairStrategy.sol
  src/interfaces/IDFMM.sol
  src/interfaces/IStrategy.sol
  src/lib/DynamicParamLib.sol
  src/lib/StrategyLib.sol
  test/ConstantSum/ConstantSumTest.t.sol
  test/ConstantSum/unit/Allocate.t.sol
  test/ConstantSum/unit/Constructor.t.sol
  test/ConstantSum/unit/GetPoolParams.t.sol
  test/ConstantSum/unit/Init.t.sol
  test/ConstantSum/unit/SetUp.sol
  test/ConstantSum/unit/Swap.t.sol
  test/ConstantSum/unit/Update.t.sol
  test/ConstantSum/unit/ValidateSwap.t.sol
  test/DFMM/unit/Init.t.sol
  test/DFMM/unit/Internal.t.sol
  test/DFMM/unit/Swap.t.sol
  test/G3M/unit/Allocate.t.sol
  test/G3M/unit/SetUp.sol
  test/LogNormal/unit/SetUp.sol
  test/NTokenGeometricMean/NTokenGeometricMean.t.sol
  test/lib/DynamicParamLib.t.sol
  test/utils/LogNormalArbitrage.sol
Labels: 🚧 DO NOT MERGE 🚧, 📃 contracts, 🔨 audit fix

#123 Flash swap feature
  src/DFMM.sol
  src/interfaces/IDFMM.sol
  src/interfaces/ISwapCallback.sol
  test/ConstantSum/unit/Swap.t.sol
  test/DFMM/unit/Swap.t.sol
  test/G3M/unit/Swap.t.sol
  test/LogNormal/LogNormalTest.t.sol
  test/LogNormal/unit/Swap.t.sol
  test/NTokenGeometricMean/NTokenGeometricMean.t.sol
Labels: 💡 feature, 🧹 improvement

#121 Feat/bring back tau
  src/CoveredCall/CoveredCall.sol
  src/CoveredCall/CoveredCallMath.sol
  src/CoveredCall/CoveredCallSolver.sol
  src/CoveredCall/CoveredCallUtils.sol
  src/CoveredCall/README.md
  src/CoveredCall/covered_call.nb
  src/DFMM.sol
  src/interfaces/IDFMM.sol
  test/ConstantSum/unit/Init.t.sol
  test/CoveredCall/unit/Allocate.t.sol
  test/CoveredCall/unit/Deallocate.t.sol
  test/CoveredCall/unit/Init.t.sol
  test/CoveredCall/unit/SetUp.sol
  test/CoveredCall/unit/Swap.t.sol
  test/G3M/unit/Allocate.t.sol
  test/G3M/unit/SetUp.sol
  test/LogNormal/unit/Init.t.sol
Labels: 🚧 DO NOT MERGE 🚧

#119 Fix/post review
  src/ConstantSum/ConstantSum.sol
  src/ConstantSum/ConstantSumMath.sol
  src/ConstantSum/ConstantSumSolver.sol
  src/DFMM.sol
  src/GeometricMean/G3MMath.sol
  src/LogNormal/LogNormal.sol
  src/NTokenGeometricMean/NTokenGeometricMeanMath.sol
  test/ConstantSum/unit/Allocate.t.sol
  test/DFMM/unit/Init.t.sol
Labels: 🚧 DO NOT MERGE 🚧, 📃 contracts, 🔨 audit fix
